# Generated by Django 3.0.5 on 2020-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item name', max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
